---
development:
  cloud_name: hlkc2hqif
  api_key: '392881411585882'
  api_secret: flvRbWM7C_r15LECJSSFoo2wkUI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hlkc2hqif
  api_key: '392881411585882'
  api_secret: flvRbWM7C_r15LECJSSFoo2wkUI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hlkc2hqif
  api_key: '392881411585882'
  api_secret: flvRbWM7C_r15LECJSSFoo2wkUI
  enhance_image_tag: true
  static_image_support: false
